name: Download OpenBao vault simulator Docker Image
on:
  workflow_dispatch: # cho phép nhấn nút chạy thủ công

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Pull and Save Docker Image
        run: |
          docker pull openbao/openbao:latest
          docker save openbao/openbao:latest -o openbao.tar

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: openbao-image # tên file khi tải
          path: openbao.tar
          retention-days: 1 # tự xóa file sau 1 ngày
      