name: Download Superset Docker Image
on:
  workflow_dispatch: # cho phép nhấn nút chạy thủ công

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Pull and Save Docker Image
        run: |
          docker pull regang/superset:ptdl-6.0.0
          docker save regang/superset:ptdl-6.0.0 -o superset.tar

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: superset-image # tên file khi tải
          path: superset.tar
          retention-days: 1 # tự xóa file sau 1 ngày
      
